### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by motornyimaksym** [maxyou/SimpleWaveform#3]
Are there possibility to make background transparent or at least not black but colored with custom color?

**Comment by maxyou** [comment]
Hi, you can use clearScreenListener to set background or any others like this:

```
    //define how to clear screen
    simpleWaveform.clearScreenListener = new SimpleWaveform.ClearScreenListener() {
        @Override
        public void clearScreen(Canvas canvas) {
            canvas.drawColor(Color.CYAN); //do anything on canvas
        }
    };
```

**Comment by motornyimaksym** [comment]
@maxyou Thank you! Have you noticed that when you using canvas.drawColor(Color.TRANSPARENT) it's make it black?

**Comment by maxyou** [comment]
@Yazon2006 I think transparent means no color. If there is no deeper background then it should be black. But I'm not very sured.
