### ISSUE TITLE
Audio Path

### ISSUE THREAD

**Issue by kosratdev** [maxyou/SimpleWaveform#4]
Hi, 

How to set audio path in local or in network, in the samples you just create random amplitude, how to set real amplitude?

thanks in advance.

**Comment by maxyou** [comment]
This code do not have function of decode an audio file. It only receive amplitude or other data to display. By my experience, I used MediaRecorder to parse audio file and get period max amplitude as sound sample data.

**Comment by kosratdev** [comment]
Ok thank you very much.
