### ISSUE TITLE
Connect AdvanceDemo2 with an audio.

### ISSUE THREAD

**Issue by aliraza96** [maxyou/SimpleWaveform#5]
I really need help in this matter asap. I want to connect this SimpleWaveForm with my audio file to make it's Waveform. So can anyone help me with this?

**Comment by maxyou** [comment]
Can you read wave data from your audio file?
Have you read the advanceDemo2 code? It's at here: https://github.com/maxyou/SimpleWaveform/blob/master/myapplication/src/main/java/com/maxproj/myapplication/SimpleWaveformDemo.java

**Comment by maxyou** [comment]
> I really need help in this matter asap. I want to connect this SimpleWaveForm with my audio file to make it's Waveform. So can anyone help me with this?

Can you read wave data from your audio file?
Have you read the advanceDemo2 code? It's at here: https://github.com/maxyou/SimpleWaveform/blob/master/myapplication/src/main/java/com/maxproj/myapplication/SimpleWaveformDemo.java

**Comment by aliraza96** [comment]
Thanks. I have done this.
